config/routes.rb
Loluv::Application.routes.draw do

  resources :petitions

	root :to => 'pages#index'

	match 'users' => 'teams#index'
	
	resources :users
  resources :teams
  
	resources :matches	
	match 'round' => 'matches#index'
	match 'round/:round' => 'matches#index', :as => :matches_round
  
  match 'teams/new/:type' => 'teams#new', :as => :teams_new_type
  match 'teams/index/:type' => 'teams#index', :as => :teams_index_type
  match 'teams/new/:type/:num' => 'teams#new', :as => :recruit_num
	
	resources :news
	match 'admin/send_email' => 'pages#admin_send_email'
	match 'admin/make_matches' => 'pages#make_matches'
	
	resources :teams do
		member do
			post 'send_welcome'
		end
	end
	
	match 'index' => 'pages#index'
	match 'info' => 'pages#info', :as => :info
	match 'info/bases' => 'pages#bases', :as => :bases
	match 'info/matchmaking' => 'pages#match_making_info', :as => :matchmakinginfo
	
	resources :user_sessions
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	
	match 'users/change_password/:id/' => 'users#change_password', :as => :change_password
	match 'users/:id/update_roles/:pos' => 'users#update_roles', :as => :update_roles
	match 'users/:id/update_seed' => 'users#update_seed', :as => :update_seed
	
	match 'new_password' => 'users#new_password', :as => :req_new_password
	match 'send_new_password' => 'users#new_password', :as => :send_new_password
	
	resources :user_sessions

end

app/models/user.rb
#!/bin/env ruby
# encoding: utf-8

class User < ActiveRecord::Base
  attr_accessible :username, :uvuser, :crypted_password, :password, :persistence_token, :role, :team_id, :verified, :position, :seed
  belongs_to :team
  has_many :news
  
  acts_as_authentic do |c|
		c.validate_password_field= false
		c.require_password_confirmation = false
    #~ c.crypto_provider = Authlogic::CryptoProviders::Sha256
		c.validates_format_of_login_field_options = {
			:with => /^[[:alnum:]\s]*$/u, 
			:message => I18n.t('error_messages.login_invalid', 
				:default => "El nombre de invocador sólo debería contener letras, número, espacios y acentos."
			)
		}
  end 

  attr_accessor :password_confirmation, :old_password, :new_password
  
  def pos_a
		pos_a = Array.new
		position.each_char do |c|
			case c
			when 't'
				pos_a << "top"
			when 'j'
				pos_a << "jungler"
			when 'm'
				pos_a << "mid"
			when 'a'
				pos_a << "adc"
			when 's'
				pos_a << "support"
			end
		end
		
		return pos_a
  end  
end

app/controllers/users_controller.rb
#!/bin/env ruby
# encoding: utf-8

class UsersController < ApplicationController
	before_filter :check_auth, :only => [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index		
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    #~ @user = User.find(params[:id])
    unless @access_granted
			redirect_to @user, notice: "No tienes permisos para tal accion."
		end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save      
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    #~ @user = User.find(params[:id])
		if @access_granted
			respond_to do |format|
				if @user.update_attributes(params[:user])
					format.html { redirect_to @user, notice: 'User was successfully updated.' }
					format.json { head :no_content }
				else
					format.html { render action: "edit" }
					format.json { render json: @user.errors, status: :unprocessable_entity }
				end
			end
		else
			redirect_to @user, notice: "No tienes permisos para tal accion."
		end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
		if @access_granted
			#~ @user = User.find(params[:id])
			@user.destroy

			respond_to do |format|
				format.html { redirect_to users_url }
				format.json { head :no_content }
			end
		else
			redirect_to @user, notice: "No tienes permisos para tal accion."
		end
  end
  
  def change_password
		@user = User.find(params[:id])
		
		valid = @user.valid_password? params[:user]["old_password"]
		
		if valid 
			@user.password = params[:user]["new_password"]
			@user.save
			@change = true
		else
			@change = false
			@false_password = true
		end
		
		render 'show'
  end
  
  def new_password
		# Ask for username and uvuser.
		#
		# If both are as expected, generate a new password and send email,
		# 	otherwise empty fields and send error.
		#
		@login_wrap = true
		
		if params[:user]
			@user = User.where(["username = ?", params[:user]["username"]]).first
			
			 if @user
				if @user.uvuser ==  params[:user]["uvuser"]
					# Correct, send email.
					
					pass = @user.randomize_password
					@user.password = pass
					mail = UserMailer.new_password_email(@user,pass).deliver
					if mail
						@user.save
						UserSession.find.destroy
						redirect_to :login, notice: "Los nuevos datos han sido enviados al email asociado a la cuenta."
					else
						UserSession.find.destroy
						@error = "Ha surgido un error al enviar el email, por favor inténtalo de nuevo o contáctanos."
					end
					
					if session = UserSession.find
						session.destroy
					end
				else
					# Incorrect: uvuser is incorrect.
					@error = "El usuario de la UV introducido no coincide con el de nuestra base de datos."
					@user = User.new
				end
			 else
			 # No user found
				@error = "No se ha encontrado ningun usuario."
				@user = User.new
			end
		else
			# No data introduced
			@user = User.new
		end
  end
  
  def update_roles
		@user = User.find(params[:id])
		
		@user.position = params[:pos]
		if @user.save
			redirect_to @user, notice: "Roles actualizados correctamente."
		else
			redirect_to @user, alert: "Ha surgido un problema actualizando los roles."
		end
  end
  
  # Seed is intended to make match-making as transparent as possible
  def update_seed
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user])
			redirect_to @user, notice: "Semilla actualizada correctamente."
		else
			redirect_to @user, alert: "Ha surgido un problema actualizando la semilla."
		end
  end
  
  def check_auth
		# Just allow user 0 && admins
		@user = User.find(params[:id])
		@access_granted = false
		
		if current_user
			if current_user.id == 1 || current_user.role == 1
				@access_granted = true
			end
		end
	end
  
end

app/views/users/_change_password.html.erb
<%= form_for(@user, :url => change_password_path(@user.id)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--
	<div class="field">
    <%= label_tag :old_password, "Contraseña anterior" %><br />
    <%= text_field_tag :old_password %>
  </div>
-->
	<% if @change %>
		<div class="notice">La contraseña ha sido cambiada.</div>
	<% elsif @false_password %>
		<div class="error">La contraseña no es correcta.</div>
	<% end %>
	<div class="field">
    <%= f.label :old_password, "Contraseña" %><br />
    <%= f.password_field :old_password %>
  </div>
  <div class="field">
    <%= f.label :new_password, "Nueva Contraseña" %><br />
    <%= f.password_field :new_password %>
  </div>
  <span class="actions">
    <%= submit_tag "Actualizar" %>
  </span>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :uvuser %><br />
    <%= f.text_field :uvuser %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <% if current_user.role == 1 || current_user.id == 1 %>
		<div class="field">
			<%= f.label :role %><br />
			<%= f.text_field :role %>
		</div>
	<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_roles.html.erb
<!--
	Sleepy dude just wrote "roles" and "positions" without distinction
-->
Roles:
<div id="user_positions">
	<% roles = ["top", "jungler", "mid", "adc", "support"] %>
	<% if @user.pos_a.length > 0 || its_me %>
		<% @user.pos_a.each do |pos| %>
			<div class="position" id="<%= pos %>"><%= pos.capitalize %><a class="remove_role">x</a></div>
			
<!--
			Delete each role from a role variable to know which are missing
-->
			<% if its_me %>
				<% roles.delete_if { |r| r == pos} %>
			<% end %>
		<% end %>
		
<!--
			Missing roles + Add role
-->
		<% if @user.pos_a.length < 5 %>
			<a class="add_role">+ Añadir rol</a>
			<div id="missing_roles">
			<% roles.each do |role| %>
				<a id="<%= role %>"><%= role %></a>
			<% end %>
			</div>
<!--
			Save
-->
		<div id="update_roles"><%= link_to "Guardar", update_roles_path(@user.id,"s") %></div>
		<% end %>
	<% else %>
		El usuario no ha definido ninguna posición
	<% end %>
</div>

app/views/users/_seed.html.erb
<% if @its_me %>
	<% 
		now = Time.now.utc;
		dead_line = Time.utc(2013, "may", 3, 13, 00, 0)
		
		dead_line_over = now <=> dead_line
	%>
	<div id="seed_form">
		<%= form_for @user, :url => update_seed_path(@user.id) do |f| %>
			Introduce cualquier texto
	
			<%= if dead_line_over == +1
				f.text_field :seed, :disabled => true
			else
				f.text_field :seed, :maxlength => 20
			end
			%>
			<%= f.submit("Enviar") %>
			<div class="spoiler">Recomendamos escribir algo que recordéis para poder comprobarlo más adelante.<br /><br />
			Para más información, revisar la <%= link_to "información de emparejamientos", matchmakinginfo_path %>.</div>
		<% end %>
	</div>
<% end %>
	

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Uv User</th>
<!--
    <th>Crypted password</th>

    <th>Persistence token</th>
    <th>Role</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
-->
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.team.name unless user.team.nil? %></td>
    <td><%= link_to 'Show', user %></td>
 <!--
		<td><%= user.uvuser %></td>
    <td><%= user.crypted_password %></td>
    <td><%= user.persistence_token %></td>
    <td><%= user.role %></td>
    <td><%= user.team_id %></td>
    
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%= link_to 'New User', new_user_path %>
-->
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new_password.html.erb
<h2>Recuperación de contraseña</h2>

<%if @error %>
	<div class="error"><%= @error %></div>
<% end %>

<%= form_for(@user, :url => send_new_password_path) do |f| %>
	<div class="field">
		<%= f.label :username, "Invocador" %><br />
		<%= f.text_field :username, :required => true %>
	</div>
	<div class="field">
		<%= f.label :uvuser, "Usuario de la UV" %><br />
		<%= f.text_field :uvuser, :required => true %>
	</div>
	<span class="actions">
    <%= submit_tag "Enviar" %>
  </span>
<% end %>

app/views/users/show.html.erb
<% @its_me = current_user && (current_user.id == @user.id)  %>

<% if @user.team.logo.file? %>
	<div id="t_logo"><%= image_tag @user.team.logo.url(:thumb) %></div>
<% end %>

<h1><%= @user.username %>
	<% if current_user && current_user.role > 0 %>
		<span class="uvuser">(<%= @user.uvuser %>@alumni.uv.es)</span>
	<% end %>
</h1>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h3><%= link_to @user.team.name, @user.team %></h3>

<% if @its_me %>
	<% if (@user.team.verified < VERIFIED_MIN) %>
		<p id="not_verified">Para verificar tu equipo tienen que entrar a su cuenta al menos <%= @verified_min %> jugadores.</p>
	<% end %>
	
	Semilla para emparejamientos:
	<%= render 'seed' %>
	
	Cambiar contraseña:
	<div id="change_password">
	<%= render 'change_password' %>
	</div>
<% end %>


<span id="back_but"><%= link_to 'Atrás', @user.team %></span>

<% if current_user && current_user.id == 1 %>
	<span id="edit_but"><%= link_to 'Editar', edit_user_path(@user) %></span>
<% end %>