config/routes.rb
Loluv::Application.routes.draw do

  resources :petitions

	root :to => 'pages#index'

	match 'users' => 'teams#index'
	
	resources :users
  resources :teams
  
	resources :matches	
	match 'round' => 'matches#index'
	match 'round/:round' => 'matches#index', :as => :matches_round
  
  match 'teams/new/:type' => 'teams#new', :as => :teams_new_type
  match 'teams/index/:type' => 'teams#index', :as => :teams_index_type
  match 'teams/new/:type/:num' => 'teams#new', :as => :recruit_num
	
	resources :news
	match 'admin/send_email' => 'pages#admin_send_email'
	match 'admin/make_matches' => 'pages#make_matches'
	
	resources :teams do
		member do
			post 'send_welcome'
		end
	end
	
	match 'index' => 'pages#index'
	match 'info' => 'pages#info', :as => :info
	match 'info/bases' => 'pages#bases', :as => :bases
	match 'info/matchmaking' => 'pages#match_making_info', :as => :matchmakinginfo
	
	resources :user_sessions
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	
	match 'users/change_password/:id/' => 'users#change_password', :as => :change_password
	match 'users/:id/update_roles/:pos' => 'users#update_roles', :as => :update_roles
	match 'users/:id/update_seed' => 'users#update_seed', :as => :update_seed
	
	match 'new_password' => 'users#new_password', :as => :req_new_password
	match 'send_new_password' => 'users#new_password', :as => :send_new_password
	
	resources :user_sessions

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :published, :title, :user_id
  
  belongs_to :user
end

app/controllers/news_controller.rb
#!/bin/env ruby
# encoding: utf-8

class NewsController < ApplicationController
  before_filter :check_auth, :only => [:edit, :update, :destroy, :new, :create]
  
  # GET /news
  # GET /news.json
  def index
		now = Time.new.utc.to_s[0..-5]
    @news = News.where("published < Datetime('#{now}')").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
		@news = News.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @news }
		end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])
    
    @news.user_id = current_user.id

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
  
  def check_auth
		@access_granted = false
		
		if current_user
			if current_user.role == 1
				@access_granted = true
			end
		end
		
		unless @access_granted
			redirect_to "/news", notice: 'No tienes permisos para tal acción.'
		end
	end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :required => true %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :cols => 80, :required => true %>
  </div>
<!--
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id, :value => current_user.id %>
  </div>
-->
	
  <div class="field">
    <%= f.label :published, "Publicar" %><br />
    <div class="spoiler">Todavía no está en funcionamiento.</div>
    <%= f.datetime_select :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Noticias</h1>

<% @news.each do |news| %>
	<div class="news">
		<div class="header">
			<h3><%= link_to news.title, news %></h3>
			<span class="author"><%= news.user.username %></span> - 
			<span class="published"><%= news.created_at %></span>
    </div>
    <div class="content">
			<% if news.content.length > 500 
				lines = news.content[0..500].lines.to_a
				
				if lines.length > 5 %>
					<td><%= news.content.lines.to_a[0..5].join('<br />').html_safe %>...</td>
				
				<% else %>
					<td><%= news.content[0..500].gsub(/\n/, '<br />').html_safe %>...</td>
				<% end %>
				<br />
				<%= link_to 'Leer más', news %>
			<% else %>
				<td><%= news.content.gsub(/\n/, '<br />').html_safe %></td>
			<% end %>
			
		<% if current_user && current_user.role == 1 %>
			<div class="buttons">
				<td><%= link_to 'Edit', edit_news_path(news) %></td>
				<td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</div>
		<% end %>
    </div>
	</div>
<% end %>
<br />

<% if current_user && current_user.role == 1 %>
	<%= link_to 'New News', new_news_path %>
<% end %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<div id="news">
		<div class="header">
			<h1><%= @news.title %></h1>
			<span class="author"><%= @news.user.username %></span> - 
			<span class="published"><%= @news.created_at %></span>
    </div>

<p>
  <%= @news.content.gsub(/\n/, '<br />').html_safe %>
</p>


<span id="back_but"><%= link_to 'Atrás', news_index_path %></span>
<% if current_user && current_user.role == 1 %>
		<span id="edit_but"><%= link_to 'Edit', edit_news_path(@news) %></span>
		<span id="delete_but"><%= link_to 'Destroy', @news, method: :delete, data: { confirm: 'Are you sure?' } %></span>
<% end %>
</div>