config/routes.rb
Loluv::Application.routes.draw do

  resources :petitions

	root :to => 'pages#index'

	match 'users' => 'teams#index'
	
	resources :users
  resources :teams
  
	resources :matches	
	match 'round' => 'matches#index'
	match 'round/:round' => 'matches#index', :as => :matches_round
  
  match 'teams/new/:type' => 'teams#new', :as => :teams_new_type
  match 'teams/index/:type' => 'teams#index', :as => :teams_index_type
  match 'teams/new/:type/:num' => 'teams#new', :as => :recruit_num
	
	resources :news
	match 'admin/send_email' => 'pages#admin_send_email'
	match 'admin/make_matches' => 'pages#make_matches'
	
	resources :teams do
		member do
			post 'send_welcome'
		end
	end
	
	match 'index' => 'pages#index'
	match 'info' => 'pages#info', :as => :info
	match 'info/bases' => 'pages#bases', :as => :bases
	match 'info/matchmaking' => 'pages#match_making_info', :as => :matchmakinginfo
	
	resources :user_sessions
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	
	match 'users/change_password/:id/' => 'users#change_password', :as => :change_password
	match 'users/:id/update_roles/:pos' => 'users#update_roles', :as => :update_roles
	match 'users/:id/update_seed' => 'users#update_seed', :as => :update_seed
	
	match 'new_password' => 'users#new_password', :as => :req_new_password
	match 'send_new_password' => 'users#new_password', :as => :send_new_password
	
	resources :user_sessions

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :date, :replay_id, :team1_id, :team2_id, :winner_id, :round
  
  def team1
		team = Team.find(team1_id) if team1_id
  end
  
  def team2
		team = Team.find(team2_id) if team2_id
  end
  
  def teams
		team0 = Team.new
		team0.name = "Ninguno"
		teams = [team1, team2, team0]
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	#~ before_filter :check_auth, :only => [:edit, :update, :new, :create]
	
  # GET /matches
  # GET /matches.json
  def index
		params[:round] ||= 1
		@round = params[:round].to_i
    @matches = Match.where("round IS #{@round}").all
    
    while @matches.size < 1 && @round < 9
			@round = @round*2
			@matches = Match.where("round IS #{@round}").all
		end

		if @matches.size < 1
			@matches = Match.all
		end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
		
    @match = Match.new
    @teams = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: "Match was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
  
  def check_auth
		@access_granted = false
		
		if current_user && current_user.role == 1
			@access_granted = true
		else
			redirect_to :matches
		end
	end
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team1_id %><br />
		<%= collection_select(:match, :team1_id, Team.all, :id, :name, :prompt => "Seleccionar equipo:") %>
  </div>
    <div class="field">
    <%= f.label :team2_id %><br />
    <%= collection_select(:match, :team2_id, Team.all, :id, :name, :prompt => "Seleccionar equipo:") %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :round %><br />
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :winner_id %><br />
<!--
    <%= f.number_field :winner_id %>
-->
    <%= collection_select(:match, :winner_id, @match.teams, :id, :name) if @match.id %>
		
  </div>
  <div class="field">
    <%= f.label :replay_id %><br />
    <%= f.number_field :replay_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<!--
<table>
  <tr>
    <th>Team1</th>
    <th>Team2</th>
    <th>Date</th>
    <th>Winner</th>
    <th>Replay</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.team1_id %></td>
    <td><%= match.team2_id %></td>
    <td><%= match.date %></td>
    <td><%= match.winner_id %></td>
    <td><%= match.replay_id %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
-->

<ul id="rounds">
	<% if @round > 7 %>
		<li><%= link_to "Octavos", matches_round_path(8), :class=>"selected" %></li>
	<% else %>
		<li><%= link_to "Octavos", matches_round_path(8) %></li>
	<% end %>
	<% if @round == 4 %>
		<li><%= link_to "Cuartos", matches_round_path(4), :class=>"selected" %></li>
	<% else %>
		<li><%= link_to "Cuartos", matches_round_path(4) %></li>
	<% end %>
	<% if @round == 2 %>
		<li><%= link_to "Semifinales", matches_round_path(2), :class=>"selected" %></li>
	<% else %>
		<li><%= link_to "Semifinales", matches_round_path(2) %></li>
	<% end %>
	<% if @round == 1 %>
		<li><%= link_to "Finales", matches_round_path(1), :class=>"selected" %></li>
	<% else %>
		<li><%= link_to "Finales", matches_round_path(1) %></li>
	<% end %>
<!--
	<li><%= link_to "Cuartos", matches_round_path(4), :class => "disabled" %></li>
	<li><%= link_to "Semifinales", matches_round_path(2), :class => "disabled" %></li>
	<li><%= link_to "Finales", matches_round_path(1), :class => "disabled" %></li>
-->
</ul>

<div id="matches" style="text-align: center;">
	<% @matches.each do |match| %>
		<% if match.winner_id == match.team1.id 
			winner_class = "winner1"
		elsif match.winner_id == match.team2.id 
			winner_class = "winner2"
		else
			winner_class = ""
		end %>
		<div class="match <%= winner_class %>">
			<a href="teams/<%= match.team1.id %>"><div class="team1" style="background-image: url('<%= image_path match.team1.logo(:thumb) %>')"></div></a>
			<div class="vs"></div>
			<a href="teams/<%= match.team2.id %>"><div class="team2" style="background-image: url('<%= image_path match.team2.logo(:thumb) %>')"></div></a>
			
			<% if current_user && current_user.role == 1 %>
				<%= link_to image_tag("edit.png", :height=>"18px"), edit_match_path(match), :class=>"edit_match" %>
			<% end %>
<!--
			<span class="spoiler"><%= match.team1.name %><br /> vs. <br /> <%= match.team2.name %></span>
-->
		</div>
	<% end %>
</div>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team 1:</b>
  <%= @match.team1_id %>
</p>

<p>
  <b>Team 2:</b>
  <%= @match.team2_id %>
</p>

<p>
  <b>Date:</b>
  <%= @match.date %>
</p>

<p>
  <b>Winner:</b>
  <%= @match.winner_id %>
</p>

<p>
  <b>Replay:</b>
  <%= @match.replay_id %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>