config/routes.rb
Loluv::Application.routes.draw do

  resources :petitions

	root :to => 'pages#index'

	match 'users' => 'teams#index'
	
	resources :users
  resources :teams
  
	resources :matches	
	match 'round' => 'matches#index'
	match 'round/:round' => 'matches#index', :as => :matches_round
  
  match 'teams/new/:type' => 'teams#new', :as => :teams_new_type
  match 'teams/index/:type' => 'teams#index', :as => :teams_index_type
  match 'teams/new/:type/:num' => 'teams#new', :as => :recruit_num
	
	resources :news
	match 'admin/send_email' => 'pages#admin_send_email'
	match 'admin/make_matches' => 'pages#make_matches'
	
	resources :teams do
		member do
			post 'send_welcome'
		end
	end
	
	match 'index' => 'pages#index'
	match 'info' => 'pages#info', :as => :info
	match 'info/bases' => 'pages#bases', :as => :bases
	match 'info/matchmaking' => 'pages#match_making_info', :as => :matchmakinginfo
	
	resources :user_sessions
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout
	
	match 'users/change_password/:id/' => 'users#change_password', :as => :change_password
	match 'users/:id/update_roles/:pos' => 'users#update_roles', :as => :update_roles
	match 'users/:id/update_seed' => 'users#update_seed', :as => :update_seed
	
	match 'new_password' => 'users#new_password', :as => :req_new_password
	match 'send_new_password' => 'users#new_password', :as => :send_new_password
	
	resources :user_sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>uvLoL - 1er Torneo de LoL de la UV</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
	<% if @self_wrapped %>
		<%= yield %>
	<% else %>
		<div id="header">
			<% @chibis = ["lee_sin", "leblanc", "yorick"]
				 @chibi_rand = rand(@chibis.length) %>
			<a href="/index" id="<%= @chibis[@chibi_rand] %>" class="logred">
			</a>
			<ul id="menu-wrapped">
<!--
				<li><%= link_to "Únete", teams_new_type_path("premade"), :class => "first" %></li>
-->
				<li><a href="/teams">Equipos</a>
					<% if current_user %>
					<ul>
						
						<li><%= link_to "Mi equipo", current_user.team %></li>
						
<!--
						<li><% link_to "Reclutamiento", teams_index_type_path('recruit') %></li>
-->
					</ul>
					<% end %>
				</li>
				<li><a href="/matches">Partidas</a></li>
				<li><a href="/news">Noticias</a>
				</li>
				<li><a href="/info">Info</a>
					<ul>
						<li><%= link_to "Bases", bases_path %></li>
						<li><%= link_to "Emparejamientos", matchmakinginfo_path %></li>
					</ul>
				</li>
				<% if current_user %>
					<li><a class="last" href="/users/<%= current_user.id %>" id="connected">Conectado</a>
						<ul>
							<li><a href="/users/<%= current_user.id %>">Perfil</a></li>
							<li><%= link_to "Desconectar", :logout  %></li>
						</ul>
					</li>
				<% else %>
				
					<li><a class="last" href="/login">Login</a></li>
				<% end %>
			</li>
<!--
			<li id="news">
				<ul>Raep Taem destroza a su oponente en la primera ronda</ul>
				<ul>Queda al descubierto: a Dantrooper le gustan los rabos</ul>
			</li>
-->
		</div>
		<% if @login_wrap %>
			<div id="wrapper" style="width:300px;">
		<% else %>
			<div id="wrapper">
		<% end %>
		
			<%= yield %>
		</div>
		<div id="footer">
		Página web desarrollada por Sikian para el <a href="http://www.uv.es/adretse/">AdR Etse</a> de la UV.<br />
		Especiales gracias a <a href="http://yanniplum.deviantart.com/">Yanniplum</a> y <a href="http://lillyfrost.deviantart.com/">Lillyfrost</a> por sus chibis!
		</div>
	<% end %>
</div>

</body>
</html>